# Docs ref: https://docs.codecov.io/docs/codecovyml-reference 
# Validation check: $ curl --data-binary @codecov.yml https://codecov.io/validate

codecov:
  token: ad499a8d-3f1a-44b1-9672-27164a1281ce
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
