# Docs ref: https://docs.codecov.io/docs/codecovyml-reference
# Validation check: $ curl --data-binary @codecov.yml https://codecov.io/validate

comment: true

ignore:
  - "adapt/loaders.py"

codecov:
  token: ad499a8d-3f1a-44b1-9672-27164a1281ce
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        base: auto    # target to compare against 
        target: auto  # target "X%" coverage to hit on project
        threshold: 1% # allow this much decrease from base
        if_ci_failed: error
    patch: off
      default:
        base: auto      # target to compare against
        target: 50%     # target "X%" coverage to hit on patch
        # threshold: 50%  # allow this much decrease on patch
    changes: false
