name: "Check docs"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install doc dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx numpydoc nbsphinx sphinx_gallery sphinx_rtd_theme
        $CONDA/bin/conda install -c conda-forge pandoc
    - name: Install adapt dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codecov
        pip install -r requirements.txt
    - name: Install adapt
      run: |
        pip install -e .
    - name: Build documentation
      run: |
        conda install pandoc
        make html
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: site/
