name: "Check docs"
on:
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install adapt dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codecov
        pip install -r requirements.txt
    - name: Install doc dependencies
      run: |
        sudo dpkg -i https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb
        pip install sphinx numpydoc nbsphinx sphinx_gallery sphinx_rtd_theme pandoc
    - name: Install adapt
      run: |
        pip install -e .
    - name: Run notebooks
      run: |
        jupyter nbconvert --inplace --to notebook --ExecutePreprocessor.kernel_name=python --execute $(find ./docs -name '*.ipynb')
    - name: Build documentation
      run: |
        mkdocs build
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: site/