name: "Publish docs online"

on:
  release:
    types: [created]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install doc dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pip install sphinx numpydoc nbsphinx sphinx_gallery sphinx_rtd_theme ipython
    - name: Install adapt dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install adapt
      run: |
        pip install -e .
    - name: Build documentation
      run: |
        sudo rm -r -f docs/*
        make html
        sudo rm -r -f docs/doctrees
        sudo rm -r -f docs/html/_sources
        sudo rm -r -f docs/html/examples/*.ipynb
        mv -v docs/html/* docs/
        sudo rm -r -f docs/html
        touch .nojekyll
    - name: Push changes to remote
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs
        git commit -m "Update docs"
        git push
